providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_REQUIREMENTS_TXT = "backend/requirements.txt"

[start]
cmd = "cd backend && python -c \"from app import db, app; app.app_context().push(); db.create_all()\" && gunicorn app:app --bind 0.0.0.0:$PORT"