[phases.build]
cmds = ["echo 'Build complete'"]

[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[start]
cmd = "cd backend && gunicorn -c ../gunicorn.conf.py"
